# Generated by Django 3.2.9 on 2021-12-03 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filename',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existingPath', models.CharField(max_length=100, null=True, unique=True)),
                ('filename', models.CharField(max_length=1024)),
                ('regdate', models.DateTimeField(auto_now_add=True)),
                ('eof', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'filename',
                'ordering': ('-regdate',),
            },
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('fileid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='detect.filename', verbose_name='fileid')),
                ('code', models.TextField()),
            ],
            options={
                'db_table': 'code',
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operatetime', models.DateTimeField(auto_now_add=True)),
                ('endtime', models.DateTimeField(auto_now=True, null=True)),
                ('cwe119', models.DecimalField(decimal_places=5, default=2, max_digits=11, null=True)),
                ('cwe120', models.DecimalField(decimal_places=5, default=2, max_digits=11, null=True)),
                ('cwe469', models.DecimalField(decimal_places=5, default=2, max_digits=11, null=True)),
                ('cwe476', models.DecimalField(decimal_places=5, default=2, max_digits=11, null=True)),
                ('cweother', models.DecimalField(decimal_places=5, default=2, max_digits=11, null=True)),
                ('filenameid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='detect.filename', verbose_name='filenameid')),
            ],
            options={
                'db_table': 'vulnerability',
                'ordering': ('-operatetime',),
            },
        ),
    ]
